name: tourism
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  sliding_up_panel: ^2.0.0
  flutter_localization: ^0.3.1
  font_awesome_flutter: ^10.8.0
  google_maps_flutter: ^2.2.8
  another_carousel_pro: ^1.0.2
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   
   - images/home/quote.png
   - images/home/text_divider.png
   - images/home/place1.jpg
   - images/home/place2.jpg
   - images/home/k.png
   - images/home/scroll.png
   - images/home/bg.jpg
   - images/home/divider.png
   - images/home/div.png
   - images/home/try.png
   - images/home/medina-sousse.png



   - images/ribat/ribat.jpg
   - images/ribat/ribat1.jpg
   - images/ribat/ribat2.JPG
   - images/ribat/ribat3.jpg
   - images/ribat/ribat4.JPG
   - images/ribat/ribat5.jpg


   - images/jemaa/jemaa1.jpg
   - images/jemaa/jemaa2.jpg
   - images/jemaa/jemaa3.jpg
   - images/jemaa/jemaa4.jpg
   - images/jemaa/jemaa5.jpg

   - images/musee/koubba/musee2.jpg
   - images/musee/koubba/musee1.jpg
   - images/musee/koubba/musee3.jpg
   - images/musee/koubba/musee4.jpg
   - images/musee/koubba/musee5.jpg
   - images/musee/koubba/musee6.jpg
   - images/musee/koubba/musee7.jpg
   - images/musee/koubba/musee8.jpg
   - images/musee/koubba/musee9.jpg
   - images/musee/koubba/musee10.jpg   


   - images/musee/darsid/darsid1.jpg
   - images/musee/darsid/darsid2.jpg
   - images/musee/darsid/darsid3.jpg
   - images/musee/darsid/darsid4.jpg
   - images/musee/darsid/darsid5.jpg


   - images/musee/Archeological/arc1.JPG
   - images/musee/Archeological/arc2.jpg 
   - images/musee/Archeological/arc3.jpg
   - images/musee/Archeological/arc4.jpg
   - images/musee/Archeological/arc5.jpg
   - images/musee/Archeological/arc6.jpg
   - images/musee/Archeological/arc7.jpg
   - images/musee/Archeological/arc8.jpg
   - images/musee/Archeological/arc9.jpg
   - images/musee/Archeological/arc10.jpg



   - images/musee/darbaba/baba1.jpg
   - images/musee/darbaba/baba2.jpg
   - images/musee/darbaba/baba3.jpg     
   - images/musee/darbaba/baba4.jpg
   - images/musee/darbaba/baba5.jpg
   - images/musee/darbaba/baba6.jpg
   - images/musee/darbaba/baba7.jpg




    

   - images/fhal.jpg
   - images/abd_qader.jpg
   


   - images/guest_house/dar_badiaa/badiaa1.jpg
   - images/guest_house/dar_badiaa/badiaa2.jpg
   - images/guest_house/dar_badiaa/badia3.jpg
   - images/guest_house/dar_badiaa/badiaa4.jpg
   - images/guest_house/dar_badiaa/badiaa5.jpg
   - images/guest_house/dar_badiaa/badiaa6.jpg
   - images/guest_house/dar_badiaa/badiaa7.jpg
   - images/guest_house/dar_badiaa/badiaa8.jpg
   - images/guest_house/dar_badiaa/badiaa9.jpg
   - images/guest_house/dar_badiaa/badiaa10.jpg
   - images/guest_house/dar_badiaa/badiaa11.jpg
   - images/guest_house/dar_badiaa/badiaa12.jpg
   - images/guest_house/dar_badiaa/badiaa13.jpg
   - images/guest_house/dar_badiaa/badiaa14.jpg
   - images/guest_house/dar_badiaa/badiaa15.jpg
   - images/guest_house/dar_badiaa/badiaa16.jpg
   - images/guest_house/dar_badiaa/badiaa17.jpg
   - images/guest_house/dar_badiaa/badiaa18.jpg



   - images/guest_house/dar_antonio/antonia4.jpg
   - images/guest_house/dar_antonio/antonia1.jpg
   - images/guest_house/dar_antonio/antonia2.jpg
   - images/guest_house/dar_antonio/antonia3.jpg
   - images/guest_house/dar_antonio/antonia5.jpg
   - images/guest_house/dar_antonio/antonia6.jpg
   - images/guest_house/dar_antonio/antonia7.jpg
   - images/guest_house/dar_antonio/antonia8.jpg
   - images/guest_house/dar_antonio/antonia9.jpg
   - images/guest_house/dar_antonio/antonia10.jpg


   - images/guest_house/dar_baaziz3/baaziz1.jpg
   - images/guest_house/dar_baaziz3/baaziz2.jpg
   - images/guest_house/dar_baaziz3/baaziz3.jpg
   - images/guest_house/dar_baaziz3/baaziz4.jpg
   - images/guest_house/dar_baaziz3/baaziz5.jpg
   - images/guest_house/dar_baaziz3/baaziz6.jpg
   - images/guest_house/dar_baaziz3/baaziz7.jpg


   - images/guest_house/dar_baaziz1/ba1.jpg
   - images/guest_house/dar_baaziz1/ba2.jpg
   - images/guest_house/dar_baaziz1/ba3.jpg
   - images/guest_house/dar_baaziz1/ba4.jpg
   - images/guest_house/dar_baaziz1/ba5.jpg
   - images/guest_house/dar_baaziz1/ba6.jpg
   - images/guest_house/dar_baaziz1/ba7.jpg
   - images/guest_house/dar_baaziz1/ba8.jpg
   - images/guest_house/dar_baaziz1/baaziz.jpg





   - images/guest_house/dar_elkbira/elkbira1.jpg
   - images/guest_house/dar_elkbira/elkbira2.jpg
   - images/guest_house/dar_elkbira/elkbira3.jpg
   - images/guest_house/dar_elkbira/elkbira4.jpg
   - images/guest_house/dar_elkbira/elkbira5.jpg
   - images/guest_house/dar_elkbira/elkbira6.jpg
   - images/guest_house/dar_elkbira/elkbira7.jpg
   - images/guest_house/dar_elkbira/elkbira8.jpg
   - images/guest_house/dar_elkbira/elkbira9.jpg
   - images/guest_house/dar_elkbira/elkbira10.jpg
   - images/guest_house/dar_elkbira/elkbira11.jpg
   - images/guest_house/dar_elkbira/elkbira12.jpg
   - images/guest_house/dar_elkbira/elkbira13.jpg
   - images/guest_house/dar_elkbira/elkbira14.jpg
   - images/guest_house/dar_elkbira/elkbira15.jpg
   - images/guest_house/dar_elkbira/elkbira16.jpg


   - images/guest_house/tiziri/tiziri1.webp
   - images/guest_house/tiziri/tiziri2.webp
   - images/guest_house/tiziri/tiziri3.webp
   - images/guest_house/tiziri/tiziri4.webp
   - images/guest_house/tiziri/tiziri5.webp
   - images/guest_house/tiziri/tiziri6.webp
   - images/guest_house/tiziri/tiziri7.webp
   - images/guest_house/tiziri/tiziri8.webp



   - images/restaurants/dar_emna/emna1.jpg
   - images/restaurants/dar_emna/emna2.jpg
   - images/restaurants/dar_emna/emna3.jpg
   - images/restaurants/dar_emna/emna4.jpg
   - images/restaurants/dar_emna/emna5.jpeg
   - images/restaurants/dar_emna/emna6.jpg
   - images/restaurants/dar_emna/emna7.jpg
   - images/restaurants/dar_emna/emna8.jpg
   - images/restaurants/dar_emna/emna9.jpg
   - images/restaurants/dar_emna/emna10.jpg
   - images/restaurants/dar_emna/emna11.jpg


   - images/restaurants/antonia/ant1.jpg
   - images/restaurants/antonia/ant2.jpg
   - images/restaurants/antonia/ant3.jpg
   - images/restaurants/antonia/ant4.jpg
   - images/restaurants/antonia/ant5.jpg
   - images/restaurants/antonia/ant6.jpg
   - images/restaurants/antonia/ant7.jpg
   - images/restaurants/antonia/ant8.jpg
   - images/restaurants/antonia/ant9.jpg
   - images/restaurants/antonia/antonia1.jpg
   - images/restaurants/antonia/antonia2.jpg


   - images/restaurants/silest/silest1.jpg
   - images/restaurants/silest/silest2.jpg
   - images/restaurants/silest/silest3.jpg
   - images/restaurants/silest/silest4.jpg
   - images/restaurants/silest/silest5.jpg
   - images/restaurants/silest/silest6.jpg
   - images/restaurants/silest/silest7.jpg
   - images/restaurants/silest/silest8.jpg
   - images/restaurants/silest/silest9.jpg



   - images/restaurants/Sofra/soffra1.jpg
   - images/restaurants/Sofra/soffra2.jpg
   - images/restaurants/Sofra/soffra3.jpg
   - images/restaurants/Sofra/soffra4.jpg
   - images/restaurants/Sofra/soffra5.jpg
   - images/restaurants/Sofra/soffra6.jpg
   - images/restaurants/Sofra/soffra7.jpg
   - images/restaurants/Sofra/soffra8.jpg





   - images/souks/el_caid/caid.jpg
   - images/souks/el_caid/caid1.jpg
   - images/souks/el_caid/caid2.jpg
   - images/souks/el_caid/caid3.jpg
   - images/souks/el_caid/caid4.jpg
   - images/souks/el_caid/caid5.jpg
   - images/souks/el_caid/caid6.jpg
   - images/souks/el_caid/caid7.jpg





        


   




   

   
   

   

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
